development:
  adapter: sqlite3
  server: localhost
  username: root 
  password:
  database: oilreporter_development
  
test: &TEST
  adapter: sqlite3
  server: localhost
  username: root 
  password:
  database: oilreporter_test

production:
  adapter: mysql
  server: localhost
  username: root 
  password:
  database: oilreporter_production

cucumber:
  <<: *TEST