default: &default
  access_key_id: AKIAIPQV3QXYKQQQVV4Q
  secret_access_key: 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
  bucket: oilspill_photos

development:
  access_key_id: AKIAIPQV3QXYKQQQVV4Q 
  secret_access_key: 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 
  bucket: oilspill_photos 

test:
  access_key_id: AKIAIPQV3QXYKQQQVV4Q 
  secret_access_key: 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 
  bucket: oilspill_photos 

production:
  <<: *default
